-- Run this in the Supabase SQL editor, then add your project URL and anon key
-- to a local .env file. The public site may only insert waitlist addresses.

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null default 'website',
  created_at timestamptz not null default now(),
  constraint waitlist_email_length check (char_length(email) between 5 and 320)
);

alter table public.waitlist enable row level security;

create policy "Anyone can join the waitlist"
on public.waitlist
for insert
to anon
with check (source = 'website');
